uses crt,k_lexica,k_syntax;
var s:string;
begin
clrscr;
overture;
afficher;
writeln;
writeln('*****************************************************************');
writeln('***************  Le r‚sultat de compilation  ********************');
writeln('*****************************************************************');
{}prog;{}
writeln;
writeln('                           Succes                                ');

readkey;
end.